# Generated by Django 4.2.7 on 2023-11-25 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_categorias_clientes_factura_productos_proveedores_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorias',
            name='nombre',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
