# Generated by Django 4.2.7 on 2023-11-30 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_productos_catproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='canProducto',
            field=models.PositiveIntegerField(default=True, verbose_name='Nombre del Producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='catProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorias', verbose_name='categoria del Producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='desProducto',
            field=models.CharField(max_length=200, verbose_name='Descripcion del Producto'),
        ),
        migrations.AlterField(
            model_name='productos',
            name='nomProducto',
            field=models.CharField(max_length=50, verbose_name='Nombre del Producto'),
        ),
    ]
